import type { Track } from "./types";

export const frontendTrack: Track = {
  id: "frontend", label: "Frontend Engineering", shortLabel: "Frontend", accent: "#ff7f9f",
  description: "React, browser performance, accessibility, state, and UI architecture.",
  questions: [
    { id: "fe-1", prompt: "A React form re-renders on every keystroke and feels slow. How would you investigate before optimizing?", followUp: "When is memoization actually harmful?", signals: ["profiler", "render cause", "state locality", "memoization cost"], idealAnswer: "Use the React Profiler and browser performance tools, identify which components rerender and why, localize state, avoid expensive work during render, and measure again. Memoization adds comparison and complexity and is harmful when work is cheap or dependencies change constantly." },
    { id: "fe-2", prompt: "How would you make a custom dropdown genuinely accessible?", followUp: "Why might a native select still be the better choice?", signals: ["keyboard", "focus", "ARIA", "screen reader"], idealAnswer: "Follow the listbox or combobox pattern precisely: labeled control, managed focus, arrow and escape behavior, correct roles/states, and screen-reader testing. Native select is more robust across devices and assistive technology when custom behavior is unnecessary." },
    { id: "fe-3", prompt: "Describe your strategy for server state versus client state in a large frontend.", followUp: "Where should derived state live?", signals: ["server cache", "URL state", "local state", "single source of truth"], idealAnswer: "Keep remote data in a server-state cache, share navigable filters in the URL, keep ephemeral UI state local, and reserve global state for true cross-cutting client concerns. Compute derived state rather than synchronizing copies." },
    { id: "fe-4", prompt: "A page has a good Lighthouse score but users report it feels slow. What do you inspect next?", followUp: "How would you catch long tasks in production?", signals: ["real user monitoring", "INP", "long task", "network waterfall"], idealAnswer: "Inspect real-user Core Web Vitals, especially INP, segment by device and route, review waterfalls and long main-thread tasks, and correlate interactions with traces. Lab scores cannot represent all devices, data, or user paths." },
    { id: "fe-5", prompt: "How do you design an error-handling experience across a frontend application?", followUp: "Which errors belong near the field versus in a global notification?", signals: ["error boundary", "recovery", "validation", "observability"], idealAnswer: "Classify errors by scope, preserve user input, provide a recovery action, use route/component boundaries for render failures, inline validation beside fields, and transient notices for non-blocking outcomes. Log technical context with correlation IDs." },
  ],
};
