import type { Track } from "./types";

export const fullstackTrack: Track = {
  id: "fullstack", label: "Python Full-stack", shortLabel: "Full-stack", accent: "#62d9ff",
  description: "APIs, databases, browser flows, security, and system trade-offs.",
  questions: [
    { id: "fs-1", prompt: "Design the request flow for a Django or FastAPI checkout endpoint from browser click to committed order.", followUp: "Where would you place the idempotency boundary?", signals: ["validation", "transaction", "idempotency", "async job"], idealAnswer: "Validate at the boundary, authenticate and authorize, use an idempotency key, commit inventory and order state in a transaction, then publish post-commit work through an outbox or queue. Return a stable resource representation." },
    { id: "fs-2", prompt: "Your React page shows stale data after an update succeeds. How would you trace the problem across the stack?", followUp: "What if the API response is fresh but a CDN serves an old page?", signals: ["network inspection", "cache key", "state invalidation", "HTTP headers"], idealAnswer: "Trace from mutation response through client cache invalidation, component state, API caching, and database reads. Inspect request IDs and cache headers. For CDN staleness, fix cache keys and revalidation or purge strategy rather than adding arbitrary client reloads." },
    { id: "fs-3", prompt: "When would you choose server-side rendering, client rendering, or static generation for one product?", followUp: "How does authentication change the choice?", signals: ["SEO", "latency", "personalization", "cacheability"], idealAnswer: "Choose per route: static for durable public content, server rendering for indexable or request-personalized pages, and client rendering for highly interactive authenticated surfaces. Authentication reduces shared cacheability and requires careful data isolation." },
    { id: "fs-4", prompt: "How do you prevent a slow database query from taking down the entire web service?", followUp: "Which metric would tell you the connection pool is the real bottleneck?", signals: ["timeout", "index", "connection pool", "backpressure"], idealAnswer: "Set query and request deadlines, cap pools, add indexes based on query plans, paginate, apply backpressure, and degrade gracefully. Pool wait time, saturation, and checked-out connections reveal pool pressure." },
    { id: "fs-5", prompt: "Give me your practical security checklist for a Python web application.", followUp: "How would you store and rotate secrets?", signals: ["CSRF", "XSS", "SQL injection", "least privilege"], idealAnswer: "Use framework-safe parameterization and escaping, CSRF controls, secure cookie settings, authorization on every object, rate limits, validation, dependency scanning, security headers, least-privilege identities, and managed secret storage with rotation." },
  ],
};
