import python from '../../backend/question_banks/python.json';
import fullstack from '../../backend/question_banks/fullstack.json';
import rag from '../../backend/question_banks/rag.json';
import genai from '../../backend/question_banks/genai.json';
import frontend from '../../backend/question_banks/frontend.json';
import aws from '../../backend/question_banks/aws.json';
import dsa from '../../backend/question_banks/dsa.json';
import type { Track, TrackId } from './types';
export const tracks = [python, fullstack, rag, genai, frontend, aws, dsa] as Track[];
export const trackMap = Object.fromEntries(tracks.map(track => [track.id, track])) as Record<TrackId, Track>;
export type { Difficulty, InterviewQuestion, Track, TrackId } from './types';
